### ISSUE TITLE
閃退

### ISSUE THREAD

**Issue by cedricccc34** [max32002/inline_bot#2]
Max大大您好，今天在使用搶票機器人時，瀏覽器一打開就閃退，不知道是不是Inline封鎖了您的程式，想麻煩您確認一下，感恩!

**Comment by max32002** [comment]
應該是您的chrome版本需要更新, 因為會自動下載最新版的chrome driver. 

類似相關問題, 參考看看:
https://max-everyday.com/2018/03/tixcraft-bot/

也可以更新到 2023-05-31 版試看看.

**Comment by cedricccc34** [comment]
了解!麻煩您了!
